from settings import *

TOTAL_JOB_SCRAPE = 15
MIN_SLEEP_SEC = 1
MAX_SLEEP_SEC = 3
WEBDRIVER_DIR = os.path.join(ASSETS_ROOT, "bin", "chromedriver.exe")
CONCURRENCY_FACTOR = 2
UPOWORK_JOBS_ONE_PAGE = 15
PAGELOAD_TIMEOUT = 10
